Sprint 1
kostyrenkoaa/yandexReact pull request #1
Opened 2023-06-03 06:53 UTC by kostyrenkoaa

2023-06-03 07:29 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая работа с `propTypes`
- Есть проверка успешности запроса
- Реализовали закрытие модалки по ESC и сделали отписку от слушателя

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У верхней и нижней булки должны быть надписи "Верх" и "Низ" соответственно.
- Верхние и нижние булки не должны скролиться и иметь иконки перемещения. У них должен быть значок замка.
- Добавьте `isRequired`  в `cardPropTypes`

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-03 07:29 UTC, andryxxa93 commented on src/components/App/App.js
> +      fetch(`${BASE_URL}/ingredients`)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-06-03 07:29 UTC, andryxxa93 commented on src/components/App/App.js
> +          console.log(err)
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к фзш api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-06-03 07:29 UTC, andryxxa93 commented on src/components/App/App.js
> +  const isOffline = false; //todo вынести в env
**Можно лучше**
У приложения не будет режима офлайн - так что необходимости в этой переменной нет.

2023-06-03 07:29 UTC, andryxxa93 commented on src/components/Modal/Modal.js
> +  }, [onRequestClose]);
**Можно лучше**
Тут можно оставить массив пустым - модалка будет открываться и закрываться один раз

2023-06-03 07:29 UTC, andryxxa93 commented on src/utils/data.js
> +export function getItems() {
**Можно лучше**
Моковые данные больше не нужны

2023-06-03 07:29 UTC, andryxxa93 commented on src/utils/prop-types.js
> +export const cardPropTypes = PropTypes.shape({
**Необходимо исправить**
После закрывающей скобки функции `shape` так же необходимо ставить `isRequired`

2023-06-03 16:21 UTC, kostyrenkoaa commented on src/utils/prop-types.js
> +export const cardPropTypes = PropTypes.shape({
Не обязательно он везде будет обязателен. Там где используется - добавлено

2023-06-03 16:23 UTC, kostyrenkoaa commented on src/components/App/App.js
> +  const isOffline = false; //todo вынести в env
Пока оставил для отладки. Проблемы с инетом, а я в дороге

2023-06-03 16:23 UTC, kostyrenkoaa commented on src/components/App/App.js
> +          console.log(err)
Согласен, но времени не так много(

2023-06-03 16:24 UTC, kostyrenkoaa commented on src/components/App/App.js
> +      fetch(`${BASE_URL}/ingredients`)
Ок. Позже вынесу тогда)

2023-06-03 16:25 UTC, kostyrenkoaa commented on src/components/Modal/Modal.js
> +  }, [onRequestClose]);
Ок. В следующем спринте - поправлю

2023-06-03 16:25 UTC, kostyrenkoaa commented on src/utils/data.js
> +export function getItems() {
Пока в пути( Нужно мне для отладки

2023-06-04 09:00 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-18 12:26 UTC, merged