Sprint 3
kostyrenkoaa/yandexReact pull request #3
Opened 2023-07-01 13:30 UTC by kostyrenkoaa

2023-07-01 13:57 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Настроены все редиректы
- Есть автологин
- Хорошая работа с формами
- Есть обновление токена, но его нужно подправить

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".
- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . Пожалуйста, посоветуйтесь с наставником.
- Обновление токена не работает из-за функции `checkResponse`. Там чтобы получить объект ошибки - необходимо сначала декодировать ответ в формат json и из него вытащить уже ошибку.
`res.json().then(res => res.message)`
- 
**Можно лучше**
- Если пользователь не авторизован и пытается попасть на защищённый маршрут — его переадресовывает на маршрут /login. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него не получилось получить доступ ранее. Это делается с помощью  return <Redirect to={location?.state?.from || '/'} />; (эти данные записываются в ProtectedRoute, а используются в Login для Redirect)

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-01 13:57 UTC, andryxxa93 commented on src/components/App/App.js
> +          <Route path="/login" element={
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-07-01 20:19 UTC, kostyrenkoaa commented
Правки внесены

2023-07-01 20:19 UTC, kostyrenkoaa commented on src/components/App/App.js
> +          <Route path="/login" element={
Да, на следующем этапе - сделаю

2023-07-02 10:07 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-07-18 10:42 UTC, merged