Sprint 5
kostyrenkoaa/yandexReact pull request #5
Opened 2023-08-06 09:11 UTC by kostyrenkoaa

2023-08-06 09:44 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовали универсальный веб-сокет
- Сокеты открываются и закрываются согласно брифу
- Хорошая типизация хранилища

Необходимо исправить:
- В проекте присутствует много `any` и `// @ts-ignore` от которых следует избавиться.

**Можно лучше**
- Нужно организовать раздельное хранение данных в хранилище Redux, получаемых от сокета для авторизованного и неавторизованного пользователей. Иначе сейчас при заходе на страницу "История заказов" сначала на пару секунд видно данные из "Ленты заказов".

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-06 09:44 UTC, andryxxa93 commented on src/components/App/App.tsx
> +        <Route path="/profile/orders" element={
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-08-06 09:44 UTC, andryxxa93 commented on src/services/middlewares/socketMiddleware.ts
> +        socket.onmessage = (event) => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-08-06 09:44 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +  const {items, bun} = useAppSelector(store => store.items);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-08-06 10:21 UTC, kostyrenkoaa commented
Можно указать к каким именно претензия по поводу ts-ignore? Остались только в подключенных стилях, и в store.ts но на прошлом ревью сказали, что это допустимо.

2023-08-06 20:30 UTC, andryxxa93 commented
**Необходимо исправить**

- Чтобы избавиться от ts-ignore там где стили необходимо создать файл `typings.d.ts` в директории `src`.
И указать в нем код. 
```
declare module '*.css' {
    interface IClassNames {
        [className: string]: string
    }
    const classNames: IClassNames;
    export = classNames;
}
```
- От большинства этих `any` можно избавиться. `any` сводит на нет всю типизацию. Желательно чтобы их вообще не было в проекте.
 
<img width="811" alt="Снимок экрана 2023-08-06 в 23 29 13" src="https://github.com/kostyrenkoaa/yandexReact/assets/60173362/82929a14-a17f-4cf9-8f9f-ff08497a4a32">

2023-08-07 17:44 UTC, kostyrenkoaa commented
В запросах оставил any на случай какой-нибудь веселой логики

2023-08-08 06:27 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-15 19:01 UTC, merged